"""Bounded tests for MarketMind résumé-module approval and master integration
(MARKETMIND_RESUME_MODULE_APPROVAL_AND_MASTER_INTEGRATION_V1).

Proves the five Bora-approved MarketMind bullet modules are genuinely present
in and reachable from the protected master via the existing derivative/patch
architecture, are not forcibly included in every derivative, introduce no
unsupported factual metadata, and leave everything else (Winter Walk, Claims,
Evidence, Experiences) byte-unchanged. No résumé is generated by this file.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC_PATH = ROOT / "src"
MASTER_PATH = ROOT / "resume" / "master" / "RESUME_MASTER_WW_V1.json"
DRAFT_PATH = ROOT / "resume" / "drafts" / "MARKETMIND_RESUME_MODULE_DRAFTS_V1.json"
WW_CLAIMS_ROOT = ROOT / "claims" / "winter_walk"
MM_CLAIMS_ROOT = ROOT / "claims" / "marketmind"
EVIDENCE_ROOT = ROOT / "evidence"
EXPERIENCE_ROOT = ROOT / "experiences"

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from claim_repository import validate_claim_repository  # noqa: E402
from evidence_repository import validate_evidence_repository  # noqa: E402
from experience_repository import validate_experience_repository  # noqa: E402
from schema_validation import build_draft202012_validator  # noqa: E402
from resume_validation import (  # noqa: E402
    build_resume_derivative,
    validate_resume_master,
)


def assert_true(condition: bool, message: str) -> None:
    if not condition:
        print(f"FAIL: {message}")
        raise SystemExit(1)


def assert_false(condition: bool, message: str) -> None:
    assert_true(not condition, message)


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


APPROVED_WORDING_BY_MODULE = {
    "MOD_MM_001_SCOPE": (
        "Built a Python/Streamlit prototype for preliminary coffee-shop "
        "market screening using documented heuristic scoring boundaries."
    ),
    "MOD_MM_002_DETERMINISTIC_AI": (
        "Separated deterministic scoring from an optional LLM narrative "
        "layer instructed not to alter scores, thresholds, status, or "
        "scenario calculations."
    ),
    "MOD_MM_003_INTEGRATION": (
        "Integrated Google Places nearby-search and U.S. Census ACS "
        "demographic data into a coffee-shop market-screening workflow."
    ),
    "MOD_MM_004_CONTROLS": (
        "Implemented a 3.5-mile geofence, a local 50-request daily limit, "
        "and retry with degraded stub fallback for failed Places or "
        "Census fetches."
    ),
    "MOD_MM_005_TESTING": (
        "Built an automated pytest suite covering the MarketMind "
        "screening pipeline."
    ),
}

LINEAGE_BY_MODULE = {
    "MOD_MM_001_SCOPE": ("CLAIM_MM_001", ["MM_SCOPE_001", "MM_BOUNDARY_001"]),
    "MOD_MM_002_DETERMINISTIC_AI": ("CLAIM_MM_002", ["MM_SCORE_001", "MM_LLM_001"]),
    "MOD_MM_003_INTEGRATION": ("CLAIM_MM_003", ["MM_PLACES_001", "MM_CENSUS_001"]),
    "MOD_MM_004_CONTROLS": (
        "CLAIM_MM_004",
        ["MM_GEOFENCE_001", "MM_RATELIMIT_001", "MM_FALLBACK_001"],
    ),
    "MOD_MM_005_TESTING": ("CLAIM_MM_005", ["MM_TEST_001"]),
}

WINTER_WALK_CLAIM_FILES = [f"CLAIM_WW_{i:03d}.json" for i in range(1, 7)]
WINTER_WALK_MODULE_IDS = [
    "MOD_WW_001_SCOPE",
    "MOD_WW_002_CONTROLS",
    "MOD_WW_003_INTAKE",
    "MOD_WW_004_SYNC",
    "MOD_WW_005_UAT",
    "MOD_WW_006_PROCESS",
]
WINTER_WALK_WORDING_BY_MODULE = {
    "MOD_WW_001_SCOPE": (
        "Defined scope and guardrails for Winter Walk's internal Google "
        "Workspace operating system, including explicit limits on CRM "
        "functionality, public dashboards, automated sending, and causal "
        "fundraising claims."
    ),
    "MOD_WW_002_CONTROLS": (
        "Implemented fail-closed email controls that block live follow-up "
        "when the kill switch, test mode, or live-followup restriction is "
        "active, before queue-level eligibility checks run."
    ),
    "MOD_WW_003_INTAKE": (
        "Built a Google Drive-to-Workbook A CSV import workflow with "
        "automated logging for successful, held, and failed runs."
    ),
    "MOD_WW_004_SYNC": (
        "Built a self-report evidence workflow that maps form responses "
        "into the Evidence Log and syncs approved updates to the "
        "Adoption Matrix with audit logging."
    ),
    "MOD_WW_005_UAT": (
        "Documented 10 passing pilot/UAT checks covering import "
        "validation, PII absence, applicability checks, and related "
        "functional scenarios."
    ),
    "MOD_WW_006_PROCESS": (
        "Mapped Winter Walk's manual OP-support workflow into a "
        "structured operating process covering evidence tracking, "
        "review, follow-up, and human approval."
    ),
}

FORBIDDEN_INFLATION_PHRASES = [
    "production-grade",
    "enterprise",
    "predictive",
    "intelligent site-selection",
    "ai-powered",
    "autonomous",
    "robust at scale",
    "fault-tolerant",
    "circuit breaker",
    "real-time analytics platform",
    "sole developer",
    "independently built the entire system",
    "without ai assistance",
    "187 passing tests",
    "all tests pass",
    "customer",
    "user adoption",
    "revenue",
    "savings",
    "—",
]


exp_result = validate_experience_repository(EXPERIENCE_ROOT)
assert_true(exp_result["valid"] is True, "experience repository invalid")
assert_true(len(exp_result["index"]) == 7, "Experience count must be 7 (4 prior + 3 CANDIDATE_SOURCE_INGESTION_V1 records)")
ev_result = validate_evidence_repository(EVIDENCE_ROOT, experience_root=EXPERIENCE_ROOT)
assert_true(ev_result["valid"] is True, "evidence repository invalid")
assert_true(len(ev_result["index"]) == 42, "Evidence count must be 42 (37 prior + 3 CANDIDATE_SOURCE_INGESTION_V1 records + 2 human-source-resolution records)")
claim_result = validate_claim_repository()
assert_true(claim_result["valid"] is True, "claim repository invalid")
assert_true(claim_result["records_checked"] == 16, "Claim count must be 16 (13 prior + 3 CANDIDATE_SOURCE_INGESTION_V1 draft claims)")
reusable = [cid for cid, rec in claim_result["index"].items() if rec.get("human_approval") is True]
assert_true(len(reusable) == 13, f"reusable claim count must be 13, got {len(reusable)}")

EVIDENCE_INDEX = ev_result["index"]
CLAIM_INDEX = claim_result["index"]

master = json.loads(MASTER_PATH.read_text(encoding="utf-8"))
master_module_schema = build_draft202012_validator(ROOT / "schemas" / "resume_module.schema.json")


# 1 & 2. All five exact approved wordings present in the protected master,
#        each independently passing the production résumé-module schema.
mm_modules_in_master = {
    m["module_id"]: m for m in master["modules"] if m["module_id"] in APPROVED_WORDING_BY_MODULE
}
assert_true(
    set(mm_modules_in_master.keys()) == set(APPROVED_WORDING_BY_MODULE.keys()),
    f"all five approved MarketMind modules must be present in the master, got {sorted(mm_modules_in_master)}",
)
for module_id, expected_wording in APPROVED_WORDING_BY_MODULE.items():
    module = mm_modules_in_master[module_id]
    assert_true(
        module["wording"] == expected_wording,
        f"{module_id} master wording must be byte-identical to Bora's approved wording",
    )
    schema_errors = list(master_module_schema.iter_errors(module))
    assert_true(
        schema_errors == [],
        f"{module_id} must pass the production resume_module schema: {schema_errors}",
    )
print("PASS 1-2: all five exact approved wordings present in the master and schema-valid.")


# 3 & 4. Exact Claim lineage and exact Evidence lineage preserved.
for module_id, (expected_claim, expected_evidence) in LINEAGE_BY_MODULE.items():
    module = mm_modules_in_master[module_id]
    assert_true(
        module["claim_ids"] == [expected_claim],
        f"{module_id} claim_ids must be exactly [{expected_claim}], got {module['claim_ids']}",
    )
    assert_true(
        module["evidence_ids"] == expected_evidence,
        f"{module_id} evidence_ids must be exactly {expected_evidence}, got {module['evidence_ids']}",
    )
    assert_true(
        CLAIM_INDEX[expected_claim]["human_approval"] is True,
        f"{expected_claim} must remain human-approved",
    )
print("PASS 3-4: exact Claim and Evidence lineage preserved for all five modules.")


# 5. No draft-only unenforced field leaked into production modules
#    (the production resume_module schema is additionalProperties:false;
#    a passing schema check above already proves this, but assert the
#    specific known draft-only field explicitly for clarity).
for module_id, module in mm_modules_in_master.items():
    assert_true(
        "human_approval" not in module,
        f"{module_id} must not carry a module-level human_approval field "
        "(not part of the production resume_module schema)",
    )
print("PASS 5: no draft-only unenforced field leaked into production modules.")


# 6. MarketMind Experience is represented only as verified repository
#    metadata permits: no new experience_sections entry was created (no
#    verified formal_title/date_range/employer relationship exists for a
#    PERSONAL_PROJECT with no employer/client/sponsor), and no MarketMind
#    module carries an invented immutable_snapshot.
master_experience_ids = {s["experience_id"] for s in master["experience_sections"]}
assert_true(
    "EXP_MM_001" not in master_experience_ids,
    "no experience_sections entry may be created for EXP_MM_001 without verified "
    "formal_title/date_range/employer data",
)
for module_id, module in mm_modules_in_master.items():
    assert_true(
        module.get("experience_id") == "EXP_MM_001",
        f"{module_id} must reference EXP_MM_001",
    )
    assert_true(
        "immutable_snapshot" not in module,
        f"{module_id} must not carry an invented immutable_snapshot "
        "(no verified organization/formal_title/date_range exists for this personal project)",
    )
    assert_true(
        module["module_type"] == "PROJECT_BULLET",
        f"{module_id} must use module_type=PROJECT_BULLET (no employment-shaped "
        "experience_sections entry backs it)",
    )
experience = json.loads((EXPERIENCE_ROOT / "EXP_MM_001.json").read_text(encoding="utf-8"))
assert_true(experience["experience_type"] == "PERSONAL_PROJECT", "EXP_MM_001 must remain PERSONAL_PROJECT")
print("PASS 6: MarketMind Experience represented only via verified repository metadata; no section invented.")


# 7 & 8. All five modules are reachable through the existing approved-module
#        selection architecture (INCLUDE_MODULE), but are NOT forcibly
#        selected into every derivative (absent from default_module_order).
assert_true(
    set(APPROVED_WORDING_BY_MODULE.keys()).isdisjoint(set(master["default_module_order"])),
    "MarketMind modules must not be part of default_module_order (would force default inclusion)",
)

identity_patch = {
    "patch_id": "PATCH_MM_APPROVAL_TEST_NOOP",
    "target_master_id": master["master_id"],
    "operations": [{"op": "REORDER_MODULES", "module_ids": master["default_module_order"]}],
}
noop_result = build_resume_derivative(
    master=master,
    patch=identity_patch,
    claim_index=CLAIM_INDEX,
    evidence_index=EVIDENCE_INDEX,
    derivative_id="DERIV_MM_APPROVAL_NOOP",
)
assert_true(noop_result["valid"] is True, "identity-patch derivative must build")
noop_included = set(noop_result["derivative"]["included_module_ids"])
assert_false(
    noop_included.intersection(APPROVED_WORDING_BY_MODULE.keys()),
    "MarketMind modules must NOT appear in a derivative that did not explicitly select them",
)

include_ops = [{"op": "INCLUDE_MODULE", "module_id": mid} for mid in APPROVED_WORDING_BY_MODULE]
include_patch = {
    "patch_id": "PATCH_MM_APPROVAL_TEST_INCLUDE",
    "target_master_id": master["master_id"],
    "operations": include_ops,
}
include_result = build_resume_derivative(
    master=master,
    patch=include_patch,
    claim_index=CLAIM_INDEX,
    evidence_index=EVIDENCE_INDEX,
    derivative_id="DERIV_MM_APPROVAL_INCLUDE",
)
assert_true(include_result["valid"] is True, f"explicit-include derivative must build: {include_result.get('errors')}")
include_included = set(include_result["derivative"]["included_module_ids"])
assert_true(
    set(APPROVED_WORDING_BY_MODULE.keys()).issubset(include_included),
    "explicitly selecting MarketMind modules via INCLUDE_MODULE must succeed",
)
assert_true(
    include_result["derivative"]["export_allowed"] is False,
    "export must remain blocked pending human review even when modules are selected",
)
print("PASS 7-8: MarketMind modules are selectable via INCLUDE_MODULE but excluded from every default derivative.")


# 9. Winter Walk master modules remain byte-identical.
for module_id in WINTER_WALK_MODULE_IDS:
    ww_module = next(m for m in master["modules"] if m["module_id"] == module_id)
    assert_true(
        ww_module["wording"] == WINTER_WALK_WORDING_BY_MODULE[module_id],
        f"{module_id} Winter Walk wording must remain byte-identical",
    )
assert_true(
    master["experience_sections"][0]["organization"] == "Winter Walk",
    "Winter Walk experience_sections organization must remain unchanged",
)
assert_true(
    master["contact"] == {
        "name": "Bora Chaush",
        "email": "bchaush@brandeis.edu",
        "phone": "+1 857 919 8421",
        "location": "Boston, MA",
        "linkedin": "linkedin.com/in/bora-chaush-msba",
    },
    "protected contact block must remain unchanged",
)
print("PASS 9: Winter Walk master modules, section, and contact block byte-identical.")


# 10 & 11. All Claims and Evidence unchanged.
ww_hashes = {name: sha256_file(WW_CLAIMS_ROOT / name) for name in WINTER_WALK_CLAIM_FILES}
mm_claim_hashes = {
    f"CLAIM_MM_{i:03d}.json": sha256_file(MM_CLAIMS_ROOT / f"CLAIM_MM_{i:03d}.json") for i in range(1, 6)
}
for name, digest in ww_hashes.items():
    assert_true(sha256_file(WW_CLAIMS_ROOT / name) == digest, f"Winter Walk claim mutated: {name}")
for name, digest in mm_claim_hashes.items():
    assert_true(sha256_file(MM_CLAIMS_ROOT / name) == digest, f"MarketMind claim mutated: {name}")
assert_true(CLAIM_INDEX["CLAIM_MM_005"]["evidence_state"] == "OBSERVED", "CLAIM_MM_005 must remain OBSERVED")
print("PASS 10-11: all Claims and Evidence unchanged; CLAIM_MM_005 remains OBSERVED.")


# 12. No unsupported factual metadata introduced (forbidden inflation scan
#     across the master's MarketMind module wording).
for module_id, module in mm_modules_in_master.items():
    wording_lower = module["wording"].lower()
    for phrase in FORBIDDEN_INFLATION_PHRASES:
        assert_true(
            phrase not in wording_lower,
            f"{module_id} contains forbidden phrase {phrase!r}",
        )
print("PASS 12: no unsupported factual/inflation language in master MarketMind wording.")


# Full master schema validation (schema + lineage + semantic + style) as an
# additional real-validator proof, not merely a hand check.
master_validation = validate_resume_master(master, claim_index=CLAIM_INDEX, evidence_index=EVIDENCE_INDEX)
assert_true(master_validation["valid"] is True, f"protected master must validate: {master_validation['errors']}")
print("PASS: protected master (with MarketMind modules integrated) passes full validate_resume_master.")


# 13. No résumé output generated as part of this milestone (no export
#     artifacts exist under resume/ beyond the master and drafts).
resume_files = sorted(p.name for p in (ROOT / "resume").rglob("*.json"))
assert_true(
    resume_files == ["MARKETMIND_RESUME_MODULE_DRAFTS_V1.json", "RESUME_MASTER_WW_V1.json", "TELUS_RESUME_MODULE_DRAFTS_V1.json"],
    f"no export/derivative/resume output file may exist under resume/: found {resume_files}",
)
print("PASS 13: no resume output generated; only the protected master and the draft/audit record exist.")


print("PASS: MarketMind resume-module approval and master integration tests completed successfully.")
