"""Bounded tests for the PROJECT_BULLET rendering contract
(PROJECT_BULLET_RENDERING_CONTRACT_V1).

Proves: BULLET (Winter Walk) behavior is unaffected; PROJECT_BULLET
modules cannot carry fabricated employment-shaped metadata; the verified
project display name is resolvable without inventing anything; and no
résumé/export artifact is generated by this milestone.
"""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC_PATH = ROOT / "src"
MASTER_PATH = ROOT / "resume" / "master" / "RESUME_MASTER_WW_V1.json"

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from claim_repository import validate_claim_repository  # noqa: E402
from evidence_repository import validate_evidence_repository  # noqa: E402
from experience_repository import validate_experience_repository  # noqa: E402
from resume_project_bullet import (  # noqa: E402
    PROJECT_MODULE_TYPE,
    resolve_project_display_name,
    validate_project_bullet_contract,
)
from resume_validation import build_resume_derivative, validate_resume_master  # noqa: E402


def assert_true(condition: bool, message: str) -> None:
    if not condition:
        print(f"FAIL: {message}")
        raise SystemExit(1)


def assert_false(condition: bool, message: str) -> None:
    assert_true(not condition, message)


exp_result = validate_experience_repository()
assert_true(exp_result["valid"] is True, "experience repository invalid")
assert_true(len(exp_result["index"]) == 2, "Experience count must remain 2")
ev_result = validate_evidence_repository(experience_result=exp_result)
assert_true(ev_result["valid"] is True, "evidence repository invalid")
assert_true(len(ev_result["index"]) == 26, "Evidence count must remain 26")
claim_result = validate_claim_repository()
assert_true(claim_result["valid"] is True, "claim repository invalid")
assert_true(claim_result["records_checked"] == 11, "Claim count must remain 11")

EVIDENCE_INDEX = ev_result["index"]
CLAIM_INDEX = claim_result["index"]
EXPERIENCE_INDEX = exp_result["index"]

MASTER = json.loads(MASTER_PATH.read_text(encoding="utf-8"))
assert_true(len(MASTER["modules"]) == 11, "master must have 11 modules")

WW_MODULE_IDS = [
    "MOD_WW_001_SCOPE",
    "MOD_WW_002_CONTROLS",
    "MOD_WW_003_INTAKE",
    "MOD_WW_004_SYNC",
    "MOD_WW_005_UAT",
    "MOD_WW_006_PROCESS",
]
MM_MODULE_IDS = [
    "MOD_MM_001_SCOPE",
    "MOD_MM_002_DETERMINISTIC_AI",
    "MOD_MM_003_INTEGRATION",
    "MOD_MM_004_CONTROLS",
    "MOD_MM_005_TESTING",
]


# 1. Existing six Winter Walk modules behave exactly as before: module_type
#    BULLET, carry a real immutable_snapshot, referenced by experience_sections.
ww_modules = {m["module_id"]: m for m in MASTER["modules"] if m["module_id"] in WW_MODULE_IDS}
assert_true(len(ww_modules) == 6, "expected 6 Winter Walk modules")
for module_id, module in ww_modules.items():
    assert_true(module["module_type"] == "BULLET", f"{module_id} must remain module_type=BULLET")
    assert_true("immutable_snapshot" in module, f"{module_id} must retain its immutable_snapshot")
    contract = validate_project_bullet_contract(module, experience_sections=MASTER["experience_sections"])
    assert_true(contract["valid"] is True, f"{module_id} (BULLET) must be out of scope for the project contract")
assert_true(
    set(WW_MODULE_IDS) == set(MASTER["experience_sections"][0]["bullet_module_ids"]),
    "all 6 Winter Walk modules must remain referenced by SEC_WW_001",
)
print("PASS 1: Winter Walk BULLET modules unaffected by the new contract.")


# 2. PROJECT_BULLET remains distinct from BULLET.
mm_modules = {m["module_id"]: m for m in MASTER["modules"] if m["module_id"] in MM_MODULE_IDS}
assert_true(len(mm_modules) == 5, "expected 5 MarketMind modules")
for module_id, module in mm_modules.items():
    assert_true(
        module["module_type"] == PROJECT_MODULE_TYPE,
        f"{module_id} must be module_type=PROJECT_BULLET",
    )
    assert_true(module["module_type"] != "BULLET", f"{module_id} must not be module_type=BULLET")
print("PASS 2: PROJECT_BULLET is structurally distinct from BULLET.")


# 3. Explicit MarketMind selection preserves module IDs and approved wording.
APPROVED_WORDING = {
    "MOD_MM_001_SCOPE": (
        "Built a Python/Streamlit prototype for preliminary coffee-shop "
        "market screening using documented heuristic scoring boundaries."
    ),
    "MOD_MM_002_DETERMINISTIC_AI": (
        "Separated deterministic scoring from an optional LLM narrative "
        "layer instructed not to alter scores, thresholds, status, or "
        "scenario calculations."
    ),
    "MOD_MM_003_INTEGRATION": (
        "Integrated Google Places nearby-search and U.S. Census ACS "
        "demographic data into a coffee-shop market-screening workflow."
    ),
    "MOD_MM_004_CONTROLS": (
        "Implemented a 3.5-mile geofence, a local 50-request daily limit, "
        "and retry with degraded stub fallback for failed Places or "
        "Census fetches."
    ),
    "MOD_MM_005_TESTING": (
        "Built an automated pytest suite covering the MarketMind "
        "screening pipeline."
    ),
}
include_patch = {
    "patch_id": "PATCH_PROJECT_BULLET_CONTRACT_TEST",
    "target_master_id": MASTER["master_id"],
    "operations": [{"op": "INCLUDE_MODULE", "module_id": mid} for mid in MM_MODULE_IDS],
}
include_result = build_resume_derivative(
    master=MASTER,
    patch=include_patch,
    claim_index=CLAIM_INDEX,
    evidence_index=EVIDENCE_INDEX,
    derivative_id="DERIV_PROJECT_BULLET_CONTRACT",
)
assert_true(include_result["valid"] is True, f"explicit MarketMind selection must build: {include_result.get('errors')}")
included_modules = {m["module_id"]: m for m in include_result["derivative"]["modules"]}
for module_id, expected_wording in APPROVED_WORDING.items():
    assert_true(
        included_modules[module_id]["wording"] == expected_wording,
        f"{module_id} wording must be preserved exactly in the derivative",
    )
assert_true(
    set(MM_MODULE_IDS).issubset(set(include_result["derivative"]["included_module_ids"])),
    "all 5 explicitly selected MarketMind modules must be included",
)
print("PASS 3: explicit MarketMind selection preserves module IDs and approved wording exactly.")


# 4. No unsupported project metadata is required or invented: the resolver
#    returns only the verified experience_name and nothing else; no date,
#    location, or title is fabricated anywhere in the contract.
for module_id, module in mm_modules.items():
    name = resolve_project_display_name(module, experience_index=EXPERIENCE_INDEX)
    assert_true(name == "MarketMind AI", f"{module_id} display name must resolve to verified 'MarketMind AI'")
    assert_true("immutable_snapshot" not in module, f"{module_id} must not carry immutable_snapshot")
missing_experience_module = {"module_type": PROJECT_MODULE_TYPE, "experience_id": "EXP_DOES_NOT_EXIST"}
assert_true(
    resolve_project_display_name(missing_experience_module, experience_index=EXPERIENCE_INDEX) is None,
    "resolver must return None (not a guess) for an unresolved experience_id",
)
print("PASS 4: no unsupported project metadata required or invented; resolver never fabricates.")


# 5. No MarketMind module becomes default-selected.
default_patch = {
    "patch_id": "PATCH_PROJECT_BULLET_DEFAULT",
    "target_master_id": MASTER["master_id"],
    "operations": [{"op": "REORDER_MODULES", "module_ids": MASTER["default_module_order"]}],
}
default_result = build_resume_derivative(
    master=MASTER,
    patch=default_patch,
    claim_index=CLAIM_INDEX,
    evidence_index=EVIDENCE_INDEX,
    derivative_id="DERIV_PROJECT_BULLET_DEFAULT",
)
assert_true(default_result["valid"] is True, "default-patch derivative must build")
assert_false(
    set(MM_MODULE_IDS).intersection(set(default_result["derivative"]["included_module_ids"])),
    "no MarketMind module may appear in a derivative that did not explicitly select it",
)
assert_true(
    set(MM_MODULE_IDS).isdisjoint(set(MASTER["default_module_order"])),
    "MarketMind modules must remain absent from default_module_order",
)
print("PASS 5: no MarketMind module is default-selected.")


# 6 & 7. Master schema, lineage, semantic (actor-attribution), and style
#        validation all pass for the real master as-is.
master_result = validate_resume_master(MASTER, claim_index=CLAIM_INDEX, evidence_index=EVIDENCE_INDEX)
assert_true(master_result["valid"] is True, f"master must validate cleanly: {master_result['errors']}")
print("PASS 6-7: master schema, lineage, and semantic/actor-attribution validation pass.")


# 8. Adversarial: fabricated employment-shaped immutable_snapshot on a
#    PROJECT_BULLET module must be rejected.
tampered_snapshot = copy.deepcopy(MASTER)
for module in tampered_snapshot["modules"]:
    if module["module_id"] == "MOD_MM_003_INTEGRATION":
        module["immutable_snapshot"] = {
            "organization": "MarketMind AI",
            "formal_title": "Founder",
            "date_range": "May 2026 - Aug 2026",
        }
tampered_result = validate_resume_master(tampered_snapshot, claim_index=CLAIM_INDEX, evidence_index=EVIDENCE_INDEX)
assert_false(tampered_result["valid"], "fabricated immutable_snapshot on a PROJECT_BULLET must fail validation")
assert_true(
    any(e.get("code") == "PROJECT_BULLET_SNAPSHOT_FORBIDDEN" for e in tampered_result["errors"]),
    "expected PROJECT_BULLET_SNAPSHOT_FORBIDDEN",
)

# Adversarial: referencing a PROJECT_BULLET from experience_sections must be rejected.
tampered_section = copy.deepcopy(MASTER)
tampered_section["experience_sections"][0]["bullet_module_ids"].append("MOD_MM_003_INTEGRATION")
tampered_section_result = validate_resume_master(
    tampered_section, claim_index=CLAIM_INDEX, evidence_index=EVIDENCE_INDEX
)
assert_false(
    tampered_section_result["valid"],
    "referencing a PROJECT_BULLET from experience_sections must fail validation",
)
assert_true(
    any(e.get("code") == "PROJECT_BULLET_IN_EXPERIENCE_SECTION" for e in tampered_section_result["errors"]),
    "expected PROJECT_BULLET_IN_EXPERIENCE_SECTION",
)
print("PASS 8: fabricated employment-shaped metadata on a PROJECT_BULLET is deterministically rejected.")


# 9. Default derivative remains unchanged (still exactly the 6 Winter Walk modules).
assert_true(
    default_result["derivative"]["included_module_ids"] == WW_MODULE_IDS,
    "default derivative must remain exactly the 6 Winter Walk modules",
)
print("PASS 9: default derivative unchanged.")


# 10. No complete résumé/export artifact exists anywhere under resume/.
resume_files = sorted(p.name for p in (ROOT / "resume").rglob("*.json"))
assert_true(
    resume_files == ["MARKETMIND_RESUME_MODULE_DRAFTS_V1.json", "RESUME_MASTER_WW_V1.json"],
    f"no export/derivative/resume output file may exist under resume/: found {resume_files}",
)
print("PASS 10: no resume/export artifact generated by this milestone.")


print("PASS: PROJECT_BULLET rendering contract tests completed successfully.")
